const assert = require('node:assert/strict');
const p = require('../frontend_src/product.js');
const term = (amount,cadence='monthly',status='active') => ({amount_usd:amount,monthly_equivalent:amount,cadence,status});
assert.equal(p.dollars(p.decimal('1.005')), '$1.01');
assert.equal(p.dollars(p.decimal('2.675')), '$2.68');
assert.equal(p.dollars(p.decimal('1e2')), '$100.00');
assert.equal(p.dollars(p.decimal('invalid')), '—');
assert.equal(p.periodDays('2024-02-20','monthly'), 29);
assert.equal(p.periodDays('2024-02-20','quarterly'), 91);
assert.equal(p.periodDays('2024-02-20','annual'), 366);
assert.equal(p.periodDays('2025-12-31','quarterly'), 92);
assert.equal(p.daysInclusive('2024-02-28','2024-03-01'), 3);
assert.equal(p.daysInclusive('2026-10-01','2026-09-01'), 0);
assert.equal(p.dollars(p.currentTotal([])), '—');
assert.equal(p.dollars(p.currentTotal([{terms:[term('200'),term('900','monthly','ended')]}])), '$200.00');
assert.deepEqual(p.priceCards('29','monthly','2024-02-15',[]), {daily:'$1.00',monthly:'$29.00',after:'$29.00'});
assert.deepEqual(p.priceCards('30','quarterly','2024-02-15',[{terms:[term('20')]}]), {daily:'$0.33',monthly:'$10.00',after:'$30.00'});
assert.equal(p.priceCards('366','annual','2024-02-15',[]).daily, '$1.00');
assert.equal(p.priceCards('10','monthly','2024-02-15',[{terms:[term(null)]}]).after, '—');
assert.deepEqual(p.wizardSteps('add'), [1,2,3]);
assert.deepEqual(p.wizardSteps('schedule'), [2,3]);
assert.deepEqual(p.wizardSteps('correct'), [2,3]);
assert.deepEqual(p.wizardSteps('end'), [3]);
const values = {name:'Same name allowed',tool_key:'codex',amount_usd:'20.00',cadence:'monthly',start_date:'2026-09-01',end_date:null};
const plan = {id:7,version:3}, chosen = {id:9};
assert.deepEqual(p.buildPlanMutation('add',values,null,null,null,false), {operation:'add',values});
assert.deepEqual(p.buildPlanMutation('schedule',values,plan,chosen,null,false), {operation:'schedule',plan_id:7,expected_version:3,effective_date:'2026-09-01',values:{amount_usd:'20.00',cadence:'monthly'}});
assert.deepEqual(p.buildPlanMutation('end',{...values,end_date:'2026-09-30'},plan,chosen,null,false), {operation:'end',plan_id:7,expected_version:3,end_date:'2026-09-30'});
assert.deepEqual(p.buildPlanMutation('correct',values,plan,chosen,null,false), {operation:'correct',plan_id:7,expected_version:3,values,term_id:9,preview:true});
assert.deepEqual(p.buildPlanMutation('correct',values,plan,chosen,{preview_token:'token'},true), {operation:'correct',plan_id:7,expected_version:3,values,term_id:9,confirmed:true,preview_token:'token'});
assert.equal(p.buildPlanMutation('correct',values,plan,chosen,{preview_token:'token'},false).preview, true);
assert.deepEqual(p.harnessCount([{state:'healthy'},{state:'partial'},{state:'failed'}]), {count:2,label:'2 harnesses',tone:'good'});
assert.deepEqual(p.harnessCount([{state:'detected_without_history'}]), {count:0,label:'No harnesses',tone:'warning'});
assert.deepEqual(p.harnessCount([]), {count:0,label:'No harnesses',tone:'quiet'});
assert.equal(p.sourceTool('claude_local'), 'claude-code');
assert.equal(p.sourceTool('cursor_csv'), 'cursor');
assert.equal(p.sourceTone('failed'), 'danger');
console.log('32 product dialog unit assertions passed');
